### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by Spok974** [waldoxhm/asus-chromebox-cn62-guado-hackintosh#1]
I try to install macOS on the same chromebox cn62 i7 but with the last version of coreboot 4.13 and I can't do nothing actually... 
Do you think it's possible to do it with your current bios firmware version (4.12)? Possible have your firmware copy please ?!
Thanks very much Bro

**Comment by waldoxhm** [comment]
Yes, coreboot version is not a problem. Just have a try after backup. you can even install Big Sur with a little modifation of config.plist

**Comment by reanyouda** [comment]
> Yes, coreboot version is not a problem. Just have a try after backup. you can even install Big Sur with a little modifation of config.plist

how ? i'm want to install bigsur but i don't know how to config.plist

**Comment by waldoxhm** [comment]
> > Yes, coreboot version is not a problem. Just have a try after backup. you can even install Big Sur with a little modifation of config.plist
> 
> how ? i'm want to install bigsur but i don't know how to config.plist

#2

**Comment by waldoxhm** [comment]
after version 4.12 ,coreboot change the way nvram stores . I updated the bios and got the boot loop today. I'll post a downgrade script these days.

**Comment by waldoxhm** [comment]
@reanyouda  bigsur version of efi is updated. I've fully tested with coreboot 4.14, I got kernel panic when boot up, it may due to the bugfix of IGPU and the way nvram stores changed. I managed to downgrade bios to 4.12  check https://github.com/waldoxhm/scripts. 1.burn a linux image to a sdcard with balenaEtcher. 2.boot cn62 to this livecd os. 3.follow the guide run the command.

**Comment by Spok974** [comment]
Mrchromebox said: if you use the firmware from another device you will run into issues with the serial number and LAN MAC address being copied
Do you thinking I can run your script without issue ?

**Comment by Spok974** [comment]
I never get the 4.12 version on my cn62, the first firmware I was instal was the 4.13...

**Comment by waldoxhm** [comment]
> I never get the 4.12 version on my cn62, the first firmware I was instal was the 4.13...
> Do you think possible to have the 4.12? Please thanks you for your work bro

@Spok974 I think it doesn‘t matter, cause both of script and bios source file are from mrchromebox, I just modified some urls to get older bios(guado-20200604.rom), besides I said I've managed to downgrade the bios to 4.12 from 4.14(I tested it my self). And even if you lose the serial and mac address, you can setup these in opencore kext.

**Comment by Spok974** [comment]
Thanks you!!  its works great 👍🏽 
I can do it with a cn60 ?

**Comment by waldoxhm** [comment]
@Spok974 You're  welcome. Of course I  can add support for cn60 in bios downgrade script. but i don't  have that device  to test, and the opencore ssdt and config.plist are vary from platforms which means you can't hacintosh cn60 with my efi partition file.So I can't help  with cn60.

**Comment by Spok974** [comment]
Thank you 
I would like get Big Sur like you, are you using python to get the .dmg ? 
have you 2 folders in your usb? Efi and com.apple.recovery.boot? 
I Try to use your efi and kext but my USB key don't boot ... if you have some idea 
Thank you

**Comment by waldoxhm** [comment]
@Spok974  redownload the efi partition file oc 0.7.2, it may help. I changed the scanpolicy to 0 in config.plist to support installation usb.

**Comment by Spok974** [comment]
Thank you I put your new efi on my usb, I've done a bootable Big Sur 11.5.2
But there I'm still stuck on the apple... 
We have the same box, same firmware, I don't know where is the issue 
Can you send me your efi please to try ?! Thanks you

**Comment by waldoxhm** [comment]
@Spok974 I tested both installer and installed os with the source efi file on github, both boot fine ,check your enviroment.

**Comment by waldoxhm** [comment]
@Spok974 because you remove the wifi and bluetooth adapter, you should edit the config.plist ,find in<code>Kernel-Add</code>  remove the whole <dict>  both of itlwm.kext , IntelBluetoothInjector.kext and IntelBluetoothFirmware.kext.
and remove these three files in EFI/OC/Kexts. refer to #3
