### ISSUE TITLE
boot not working on bigsur 

### ISSUE THREAD

**Issue by reanyouda** [waldoxhm/asus-chromebox-cn62-guado-hackintosh#2]
i also got cn62 with same spec
i'm trying to install with ur EFI but it not working .
just show apple logo and back to bios :(

**Comment by waldoxhm** [comment]
It is SAID in readme file, that EFI is for osx 10.15.7. And I have already upgraded my device to osx11.2.3, Here is the EFI 
 attachment which support big sur with no description.
[EFI_big_sur.zip](https://github.com/waldoxhm/asus-chromebox-cn62-guado-hackintosh/files/6759694/EFI_big_sur.zip)
MD5:96f5e42698846108380365ecc2a8ffb3

**Comment by waldoxhm** [comment]
maybe your bios version is higher than 4.12，try to downgrade.

**Comment by andypastor** [comment]
I am using your version (osx catalina 10.15.7 with opencore 0.6.1 ) and trying to upgrade to big sur but when I use EFI-Fakesmc-OC0.7.2 I dont see the com.apple.recovery.boot partition, only:

1. MacOS
2. Recovery 10.15.7
3. Reset NVRam

**Comment by waldoxhm** [comment]
@andypastor you can install big sur directly in App Store.

**Comment by waldoxhm** [comment]
@andypastor Set scanpolicy to 0 in oc config.plist would help. I updated the source,fixed it, redownload and  try again.

**Comment by andypastor** [comment]
@waldoxhm  thank you.
