### ISSUE TITLE
大神您好 请问 更换了BMC94360HMB网卡以后 安装时报错 是否正常

### ISSUE THREAD

**Issue by juvechina** [waldoxhm/asus-chromebox-cn62-guado-hackintosh#3]
大神您好 请问 更换了BMC94360HMB网卡以后 安装时报错 是否正常

**Comment by waldoxhm** [comment]
你最起码要把config.plist-Kernel-Add中itlwm.kext（无线网卡驱动）、 IntelBluetoothInjector.kext、IntelBluetoothFirmware.kext（蓝牙驱动）三项的<key>Enabled</key>    从<true/>改为<false/>，才能引导起来。最好整项删掉(原装intel的无线和蓝牙驱动对你没用了)，对应kext也删除，然后自己找BMC94360HMB卡对应的驱动，加到kext文件夹和config.plist里去

**Comment by juvechina** [comment]
OK 我回去把老的网卡先装上试试 多谢
