### ISSUE TITLE
奇怪的网络问题

### ISSUE THREAD

**Issue by superfee1** [waldoxhm/asus-chromebox-cn62-guado-hackintosh#5]
你好，我也有一台华硕CN62，按照你的efi文件安装了bigsur，系统偏好设置里面有两个网络连接（“以太网”和“以太网2”），我猜测是不是“以太网”是真正的有线网络（rtl8111网卡），另一个“以太网2”是给intel7260用的。
现在上网遇到比较奇怪的问题，必须把有线网的网线拔出，把“以太网2”手动设置IP，并且用heliport连接2.4gWiFi才能上网，使用5gWiFi的话显示已连接但无法连接互联网，插上网线则2.4G网络也不能联网了。
试了好久也不知道怎么解决，想请你帮我分析一下怎么解决，在此谢过。

**Comment by waldoxhm** [comment]
以太网是网卡，以太网2是Wi-Fi，Wi-Fi只能用heliport连。以太网2不需要配置，设置dhcp应该就行，5g是驱动兼容不好，无解。插上网线以后，因为以太网在以太网2上面，自然是优先网线，2.4连着但是不使用。
